# Generated by Django 5.0.6 on 2024-06-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zedse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
